config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'destinations#index'

  get 'information' => 'welcome#information'

  resources :destinations

end

app/models/destination.rb
class Destination < ActiveRecord::Base
 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    # @destinations = Destination.all
    if params[:country]==nil
      @destinations = Destination.all
    else
    @destinations = Destination.where(country: params[:country].titleize)
  end
  @my_countries = Destination.select(:country).distinct.order(:country)

end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar)
    end
  
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination)  do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Title" %><br>
    <%= f.text_field :city, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label "Medium" %><br>
    <%= f.text_field :country , class: 'form-control'%>
  </div>
  <div class = 'form-group'>
      <%=f.label "Photo"%><br>
      <%=f.file_field :avatar%>
  </div>
  <div class="form-group">
    <%= f.label "Price" %><br>
    <%= f.number_field :population, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description , class: 'form-control', rows: '2'%>
  </div>
  <div class="actions">
    <%= f.submit "Add Artwork" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Edit Artwork</h1>

<%= render 'form' %>

<%= link_to 'More Detail', @destination %> |
<%= link_to 'Back to Gallery', destinations_path %>

app/views/destinations/index.html.erb
<h1>Gallery</h1>

<div class='row'>
  <div class = 'col-md-12'>
    <ul class = 'nav nav-pills' role = 'tablist'>
<li><%= link_to "All media", destinations_path, class: "active" %> </li>
  <% @my_countries.each do |c| %>
    <li><%= link_to "#{c.country}", controller: 'destinations', country: "#{c.country}"%></li>
<%end%>
    </ul>
  </div>
</div>

<div class=row>
    <% @destinations.each do |destination| %>
      <div class = 'col-md-4'>
          <div class = "panel panel-default">
            <div class = 'panel-body'>
        <h2>Title: <strong><%= destination.city %></h2></strong>
        <h3>Medium: <strong><%= destination.country %></h3></strong>
        <% if destination.avatar_file_name != nil%>
          <%=image_tag destination.avatar.url(:medium), class: 'img-responsive'%>
          <%end%>
          <p>Posted on <%=destination.created_at.strftime("%m/%d/%Y")%></p>
          <p></p>
          <%if can? :manage, destination%>
        <div class = 'btn-group'>
        <%= link_to 'More detail', destination, class: 'btn btn-default'%>
        <%= link_to 'Edit', edit_destination_path(destination), class: 'btn btn-default'%>
        <%= link_to 'Delete', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'%>
        </div>
        <%end%>
      </div> <!-- end 3-col grid-->
    </div>
  </div>
    <% end %>
</div> <!-- end row-->

<br>
  

<div class='row'>
  <div class = 'col-md-4'>
<p>
  <%if can? :manage, @destinations%>
<%= link_to 'Add New Artwork', new_destination_path, class: 'btn btn-default'%>   
<%end%>
</p>
</div>
</div>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Title:
  <strong><%= @destination.city %></strong>
</h1>

<%= image_tag @destination.avatar.url (:medium)%>

<h3>
	Price:
	<strong>$<%= @destination.population %></strong>
</h3>

<h3>
  Medium:
  <strong><%= @destination.country %></strong>
</h3>

<p>
  Description:
  <%= @destination.description %>
</p>

<div class = 'btn-group'>
<p>
<%= link_to 'Edit', edit_destination_path(@destination), class: 'btn btn-default'%> 
<%= link_to 'Back to Gallery', destinations_path, class: 'btn btn-default'%>
</p>
</div>