config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  root 'destinations#index'

  get 'information' => 'welcome#information'

  resources :destinations

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
      <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Nancy Donahue Art</title>

  	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"%>
	<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"%>
	<%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Poiret+One|Josefin+Sans:400,600"%>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"%>
  	
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><li><%= link_to "Gallery", destinations_path%></li></li>
        <li><%= link_to "Contact", information_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="divider"></li>
            <li><a href="#">Clay</a></li>
            <li class="divider"></li>
            <li><a href="#">Piece 1</a></li>
            <li><a href="#">Piece 2</a></li>
            <li class="divider"></li>
            <li><a href="#">Photographs</a></li>
            <li class="divider"></li>
            <li><a href="#">Piece 1</a></li>
            <li><a href="#">Piece 2</a></li>
          </ul>
        </li>
      </ul>
       <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Admin Creation", new_user_registration_path%>
          <li> <%= link_to "Admin Login", new_user_session_path%>
            <li> <%= link_to "Logout", destroy_user_session_path,:method => :delete%>
       </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class=container>
<%= yield %>
</div>

</body>
</html>